# Libraries
import socket # For TCP/IP communication
import time # For time delays
import subprocess # For launching Unity executable
import platform # For OS detection
import os # For file path handling

# -------------------------------------------------

# Function to check and set execute permissions for the Unity executable
def secure_permission_to_execute(path):
    
    # Check if the file have execute permissions
    if not os.access(path, os.X_OK):
        print(f"\nThe file {path} does not have execute permissions. Adding permissions...")
        subprocess.run(["chmod", "+x", path], check=True)

# -------------------------------------------------

# Launch the Unity application
def launch_unity():
    
    # Detect the operating system
    system = platform.system()
    
    if system == "Windows": # Path to the .exe generated by Unity
        UNITY_EXE = r"C:\Users\mauri\Documents\git\CubeTest\Export\Windows\CubeTest.exe"

    elif system == "Linux": # Path to the executable file generated by Unity on Linux
        UNITY_EXE = r"/home/mau/Documents/git/CubeTestPython/Export/Linux/CubeTest.x86_64"
        secure_permission_to_execute(UNITY_EXE)
        
    else:
        raise Exception("Unsupported operating system") # Unsupported OS

    # Check if the file exists
    if not os.path.exists(UNITY_EXE):
        raise FileNotFoundError(f"Executable not found in: {UNITY_EXE}")

    # Launch Unity executable
    print(f"\nLaunching Unity: {UNITY_EXE}")
    return subprocess.Popen(UNITY_EXE)

# -------------------------------------------------

# Attempt to connect to the Unity TCP server
def connect_to_unity(host='localhost', port=5005, retries=10):
    
    # Create a TCP socket
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    
    # Set a timeout for the socket connection
    for i in range(retries):
        
        # Try to connect to the Unity server
        try:
            
            # Set a timeout of 1 second for the connection attempt
            sock.connect((host, port))
            print("\nConnected to Unity")
            return sock
        
        except ConnectionRefusedError:
            
            # If connection is refused, wait and retry
            print(f"Attempt {i+1}: Waiting for connection...")
            time.sleep(1)
    
    # If connection fails after retries, raise an error
    raise ConnectionError("Could not connect to Unity")

# -------------------------------------------------

# Send a message to Unity
def send(sock, message):
    
    # Send the message followed by a newline character
    sock.sendall((message + "\n").encode("utf-8"))

# -------------------------------------------------

# Receive a message from Unity
def receive(sock):
    
    # Receive data in chunks until a newline character is found
    data = b""
    
    # Loop until a newline character is found in the received data
    while not data.endswith(b"\n"):
        
        # Receive data in chunks of 1024 bytes
        chunk = sock.recv(1024)
        
        # If no data is received, it indicates that the connection has been closed
        if not chunk:
            raise ConnectionAbortedError("\nConnection closed by Unity")
        
        # Append the received chunk to the data
        data += chunk
    
    # Decode the received data and strip any leading/trailing whitespace
    return data.decode("utf-8").strip()

# -------------------------------------------------

# Convert received string into list of (x, y, z) tuples
def str_to_pos_list(data_str):
    
    # Split the string by semicolons, convert each part into a tuple of floats, and filter out empty strings
    return [
        tuple(map(float, part.split(",")))
        for part in data_str.split(";")
        if part.strip()
    ]

# -------------------------------------------------

# Convert list of (x, y, z) tuples into formatted string
def format_pos_list(positions):
    
    # Join the list of tuples into a string with each tuple formatted as "x,y,z"
    return ";".join([f"{x},{y},{z}" for (x, y, z) in positions])

# -------------------------------------------------

# Main routine to run communication with Unity
def main():
    
    # Launch Unity and establish connection
    unity_process = None
    
    # Wait for Unity to initialize
    try:
        
        # Wait for a few seconds to allow Unity to start
        sock = connect_to_unity()

        # Send initial command to Unity
        for _ in range(120):  # Run X iterations (just for testing)
            
            # Request positions from Unity
            send(sock, "GET_POS")
            
            # Receive positions from Unity
            raw_response = receive(sock)
            
            # Print the raw response for debugging
            positions = str_to_pos_list(raw_response)
            print("\nReceived positions from Unity: ", positions)

            # Move each cube 0.1 units on the X axis (just for testing)
            print("Calculating new positions...")
            new_positions = [
                (round(x + 0.1, 2), round(y, 2), round(z, 2))
                for (x, y, z) in positions
            ]
            
            # Send new positions to Unity
            send(sock, f"SET_POS:{format_pos_list(new_positions)}")
            print("Sent new positions to Unity: ", new_positions)

            # Delay to control the rate of communication
            time.sleep(0.02) # 20ms delay to secure that Unity is not overloaded

    # Handle exceptions during communication
    except Exception as e:
        
        # Print the error message
        print("Error during communication: ", e)
        
    # Finally block to ensure resources are cleaned up
    finally:
        
        send(sock, "EXIT")

        # Close the socket and terminate the Unity process
        sock.close()
        if unity_process:
            unity_process.terminate()
        print("\nConnection closed, Unity terminated.\n")

# -------------------------------------------------

# Main function to run the script
if __name__ == "__main__":
    main()
